# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 85fcf0ae14d269e15a90016b3e9d7787f35ad307d5b7e845f319ffea9378617c063d6a917300c486928fca445adf0dc6764731c194d4fa7eb82572a4478a537c

test:
  secret_key_base: 94485c799612fad0f423dc9cf806c7dee53b519345a8e2b56ea6d2a9b87beae5859904cb5ad56ab99727fa0e188480428a37679f96103a611f21b4c963e15c24

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
